### ISSUE TITLE
Wrapper for the While loop

### ISSUE THREAD

**Issue by Steve0Greatness** [GenericProgrammer1234/JSONConnect#1]
Most Python parsers when looking for the primary Python file will check if `if __name__ == "__main__"` is at the bottom of Python files. I'd suggest a change such as:
```python
if __name__ == "__main__":
    while True:
        txt = input("> ")
        if txt:
            parse(txt)
```

**Comment by GenericProgrammer1234** [comment]
Thanks, I will implement it.
