### ISSUE TITLE
Use Match Case instead of If statements

### ISSUE THREAD

**Issue by Steve0Greatness** [GenericProgrammer1234/JSONConnect#2]
Match Case runs faster than `if`s and requires less duplicated booleans. Here's about how it would be implemented:
```python
match command:
     case "create": ...
     case "delete": ...
     case ...: ...
```
In order to handle cases in which no other cases apply, use an underscore(`_`) instead:
```python
match command:
     case ...: ...
     case _:
          print(f"Command doesn't exist: {command}")
```

**Comment by GenericProgrammer1234** [comment]
I have never really used match before but I know how it works. I can try but it will take a while.

**Comment by GenericProgrammer1234** [comment]
Resolved.
